# Dev profile (use -Pdev if you want this)
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/bricklink}
server.port=${SERVER_PORT:8080}

bricklink.baseUrl=${BRICKLINK_BASE_URL:https://api.bricklink.com/api/store/v1}
bricklink.inventoryEndpoint=${BRICKLINK_INVENTORY_ENDPOINT:/inventories}
bricklink.consumerKey=${BRICKLINK_CONSUMER_KEY:}
bricklink.consumerSecret=${BRICKLINK_CONSUMER_SECRET:}
bricklink.token=${BRICKLINK_TOKEN:}
bricklink.tokenSecret=${BRICKLINK_TOKEN_SECRET:}